### ISSUE TITLE
Create a better logo

### ISSUE THREAD

**Issue by blacs30** [blacs30/calibre_opds#2]
Maybe something with a book and the sync arrows like [here](https://lh3.googleusercontent.com/1fjbxyMZaSYVF6C2tURGBVlTIHMqZpPYi6cjqC24VBgURgjhSz34XM6DtIYO3nlhTiUy17UROyRMLEzmSRxRGH0=h200):

**Comment by dugite-code** [comment]
Thought I would whip something up, for your consideration: https://github.com/dugite-code/Icons/tree/be89c81e04a2e69d826af91a40f808944aee1ef1/calibre_opds

General Logo
<img src="https://github.com/dugite-code/Icons/raw/be89c81e04a2e69d826af91a40f808944aee1ef1/calibre_opds/Logo.svg?sanitize=true" width="80" align="left">
<br><br><br>
Inverted color favicon
<img src="https://github.com/dugite-code/Icons/raw/be89c81e04a2e69d826af91a40f808944aee1ef1/calibre_opds/favicon.svg?sanitize=true" width="80" align="left">

**Comment by blacs30** [comment]
That looks very much what I imagined. Thanks a lot!
I would like to use the general Logo, and a b/w version of the favicon for the settings navigation logo (without the blue background)

Is it okay for you if I list you in the credits paragraph as contributor and add the logos to this repo?

**Comment by dugite-code** [comment]
Sure thing, just glad to help

**Comment by dugite-code** [comment]
Plain Black and White
<img src="https://github.com/dugite-code/Icons/raw/30d9ea6b1febf9a50a1ac728100b1e2a51367bf1/calibre_opds/BW_icon.svg?sanitize=true" width="80" align="left">
<br><br><br>
Inverted
<img src="https://github.com/dugite-code/Icons/raw/463edf61b0c55ec1e3834e8760f2d54133ffab86/calibre_opds/BW_Invert_icon.svg?sanitize=true" width="80" align="left">
<br><br><br>
You can pull any of the icons directly from my [icon repo](https://github.com/dugite-code/Icons/tree/master/calibre_opds) or I can open a pull request if you would prefer

**Comment by blacs30** [comment]
Thank you. I will add them.
