### ISSUE TITLE
Incorrect url

### ISSUE THREAD

**Issue by byaaka** [blacs30/calibre_opds#3]
url as ../index.phpapps/calibre_opds/index.php
I think need to correct it by change in file personal.php by
$tmpl->assign('concosFeedUrl', Util::linkToAbsolute('', 'index.php') . '/apps/calibre_opds/index.php');

**Comment by blacs30** [comment]
Hi @byaaka ,

thanks for reporting this. 
So The url is displayed wrong in the "Additional Settings" for the user?

For me looks like this right after installing:

```
OPDS URL: https://nc.examle.com/apps/calibre_opds/index.php
Use your Nextcloud username and password/application password.
```

Do you have enything in the nextcloud config for:
  'overwrite.cli.url' => 'https://nc.example.com',`

Edit:
Will push an update in the late evening I guess

**Comment by blacs30** [comment]
I've release [version 0.9.1](https://github.com/blacs30/calibre_opds/releases/tag/0.9.1) 
which should fix your reported issue.
